services:
  - type: web
    name: content-whisper-scribe
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 